title: Blog
email: hardiron@gmail.com
description: >-
 ©2019
baseurl: ''
url: 'https://fpekdemir.github.io'
twitter_username: hard_zess
github_username: fpekdemir
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-admin

